#!/bin/sh
set -e

if [ "$1" = remove ] || [ "$1" = deconfigure ]; then
    systemctl disable --now amp-panel.service amp-panel-network-agent.service \
        >/dev/null 2>&1 || true
fi

#DEBHELPER#
exit 0
